export const questions = [
  {
    id: 1,
    qs: "من آدم نگرانی هستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 2,
    qs: "من دوست دارم همیشه آدم های زیادی دور و برم باشند",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 3,
    qs: "من دوست ندارم وقتم را با خیال بافی هدر بدهم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 4,
    qs: "من سعی می کنم با دیگران خوش رفتار و مودب باشم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 5,
    qs: "من چیزهای خودم را مرتب و پاکیزه نگه می دارم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 6,
    qs: "من اغلب خودم را کمتر از دیگران حس می کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 7,
    qs: "من لبخند زدن به دیگران و بیرون رفتن با انها را کار آسانی می دانم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 8,
    qs: "من وقتی روش درست انجام یک کار را پیدا کنم به همان می چسبم و ادامه می دهم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 9,
    qs: "من اغلب با اعضای خانواده بگو نگو دارم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 10,
    qs: "من به خوبی می توانم طوری برنامه ریزی کنم که کارهایم به موقع انجام شوند",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 11,
    qs: "وقتی من زیر بار یک استرس بزرگ هستم بعضی مواقع احساس می کنم دارم از هم می پاشم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 12,
    qs: "من خودم را لزوما آدم امیدواری نمی دانم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 13,
    qs: "نگاه کردن به نظم حاکم بر طبیعت و زیبایی هنرها برای من بسیار جالب است",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 14,
    qs: "بعضی از مردم من را آدم خودخواهی می دانند",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 15,
    qs: "من در کارهایم خیلی با برنامه نیستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 16,
    qs: "من به ندرت احساس تنهایی و دل افسردگی می کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 17,
    qs: "من واقعا از صحبت کردن با دیگران لذت می برم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 18,
    qs: "من معتقدم که اگر به دانشجویان اجازه بدهند که به سخنرانی های بحث بر انگیز و متناقض گوش دهند، آن ها سردرگم و گمراه می شوند",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 19,
    qs: "من بیشتر ترجیح می دهم که با دیگران همکاری کنم تا با آن ها رقابت کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 20,
    qs: "من سعی می کنم وظایفی که بر عهده ام هست را با وجدان کار انجام دهم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 21,
    qs: "حس می کنم اغلب اوقات دچار تنش و وحشت زدگی هستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 22,
    qs: "من ترجیح می دهم در جایی باشم که فعالیت وجود داشته باشد",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 23,
    qs: "خواندن یک شعر تاثیر ناچیزی بر من دارد یا این که اصلا تاثیری ندارد",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 24,
    qs: "معمولا من در مورد مقاصد دیگران بدگمان و عیب جو هستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 25,
    qs: "من دارای اهداف مشخصی هستم و برای این اهداف برنامه دارم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 26,
    qs: "من بعضی وقت ها کاملا احساس بی ارزشی می کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 27,
    qs: "من معمولا ترجیح می دهم کارها را به تنهایی انجام دهم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 28,
    qs: "من معمولا غذاهای جدید و نا آشنا را امتحان می کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 29,
    qs: "من عقیده دارم که اکثر مردم اگر به آن ها اجازه داده شود می خواهند از آدم امتیاز به دست آورند",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 30,
    qs: "من قبل از شروع هر کاری وقت زیادی را تلف می کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 31,
    qs: "من به ندرت خودم را ترسو یا مضطرب می دانم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 32,
    qs: "من اغلب احساس می کنم که پر از نیرو و انرژی هستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 33,
    qs: "من به ندرت متوجه می شوم که احساساتم در محیط های مختلف فرق می کند",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 34,
    qs: "بیشتر مردمانی را که می شناسم مرا دوست دارند",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 35,
    qs: "من برای دستیابی به اهداف خودم سخت تلاش می کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 36,
    qs: "اغلب از نحوه برخورد دیگران با من عصبانی می شوم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 37,
    qs: "من آدم بشاش و دارای روحیه بالایی هستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 38,
    qs: "من معتقدم که برای اخذ تصمیم درباره موضوعات اخلاقی باید به مقامات دینی خودمان اقتدا کنیم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 39,
    qs: "بعضی از افراد فکر می کنند من آدم سرد و حسابگری هستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 40,
    qs: "وقتی به انجام کاری را متعهد می شوم مردم می توانند همیشه مطمئن باشند که کار را پیگیری می کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 41,
    qs: "اغلب وقتی کارها طبق نقشه پیش نمی رود یا اشتباه از آب در می آید احساس دلسردی می کنم و می خواهم آن را نیمه تمام رها کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 42,
    qs: "من آدم خوش بینی نیستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 43,
    qs: "گاهی وقتی که شعری می خوانم یا به یک اثر هنری نگاه می کنم یک حالت یاس یا موجی از برافروختگی را در خودم تجربه می کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 44,
    qs: "من در رفتار و نظر خود آدم سخت و بی انعطافی هستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 45,
    qs: "گاهی آن قدری که خودم می خواهم، قابل اعتماد نیستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 46,
    qs: "من به ندرت افسرده یا غمگین می شوم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 47,
    qs: "همه زندگی و کارهای من با سرعت طی می شوند",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 48,
    qs: "من علاقه ای به تامل و تفکر در مورد ماهیت جهان یا وضعیت انسان ندارم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 49,
    qs: "اغلب سعی می کنم با فکر و با ملاحظه باشم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 50,
    qs: "من آدم سازنده و مولدی هستم که همیشه کارها را به ثمر می رساند",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 51,
    qs: "من اغلب احساس درماندگی می کنم و میل دارم شخص دیگری را مسائلم را حل کند",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 52,
    qs: "من شخص بسیار فعالی هستم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 53,
    qs: "من خیلی کنجکاوم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 54,
    qs: "من اگر اشخاصی را دوست نداشته باشم از آن ها پنهان نمی کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 55,
    qs: "به نظر نمی رسد هرگز بتوانم کارهای خود را نظم و ترتیب بدهم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 56,
    qs: "بعضی وقت ها من طوری احساس خجالت می کنم که دلم می خواهد خودم را از دیگران پنهان کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 57,
    qs: "من ترجیح می دهم راه خودم را بروم تا اینکه رهبر دیگران باشم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 58,
    qs: "من اغلب از بازی کردن با نظریه ها و افکار انتزاعی لذت می برم",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
  {
    id: 59,
    qs: "اگر نیاز باشد من حاضرم از افراد دیگر برای رسیدن به مقاصد خودم استفاده کنم",
    an: [
      { key: 1, label: "کاملا موافق", value: 0, default: false },
      { key: 2, label: "موافق", value: 1, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 3, default: false },
      { key: 5, label: "کاملا مخالف", value: 4, default: false },
    ],
  },
  {
    id: 60,
    qs: "من سعی می کنم کارهایم در حد عالی باشد",
    an: [
      { key: 1, label: "کاملا موافق", value: 4, default: false },
      { key: 2, label: "موافق", value: 3, default: false },
      { key: 3, label: "بی تفاوت", value: 2, default: false },
      { key: 4, label: "مخالف", value: 1, default: false },
      { key: 5, label: "کاملا مخالف", value: 0, default: false },
    ],
  },
];
